TS-399: add ES, IT and PT languages
getkevin/kevin-woocommerce pull request #17
Opened 2022-05-10 19:28 UTC by tomas-maciulis

Added languages and removed copyright templates from translation files

2022-05-11 05:25 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "Creditor account field must valid IBAN (Ex: LT01234567891011121314)."
Our English translations was not even fixed before we moved to another languages, what a disappointment...

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "EndpointSecret"
Would be good to add a space and name it `Endpoint Secret`

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "Your IBAN must be from the agreement with kevin.   "
why do we have spaces at the end?

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "Redirect user to make payments on bank side."
on `a` bank side

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "kevin. Refund status changed to "
is or has changed to

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "kevin. Payment status changed to "
is or has changed to

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "kevin. Payment started."
has started

2022-05-11 05:34 UTC, saltanovas commented on languages/woocommerce-gateway-getkevin-es_ES.po
> +msgid "kevin. Exception: Bad client credentials"
How this message is different from the `includes/class-wc-getkevin-gateway.php:99`? I do not really like the `kevin. Exception` beginning

2022-06-08 19:16 UTC, saltanovas requested changes

2022-06-08 19:16 UTC, saltanovas commented on includes/class-wc-getkevin-gateway.php
> +            $statusGroup = isset($_GET['statusGroup']) ? $_GET['statusGroup'] : null;
Could you tell me what's a default behaviour of the `$_GET` method when query parameter is not defined? Do we really need to convert the result to `null` if not defined?

2022-06-10 09:28 UTC, saltanovas requested changes
Revert the [e203552](https://github.com/getkevin/kevin-woocommerce/pull/17/commits/e203552f85e0b1d9624c579fe50b7d45283446e4) commit and we will wait for missing base English translations to the ES, IT and PT languages :)

2022-06-14 18:38 UTC, saltanovas requested changes
Language keys was changed but not applied to the code? The complexity of the pull request has grown a lot... :(

2022-06-29 09:10 UTC, KubaJM approved these changes

2022-06-29 10:53 UTC, saltanovas approved these changes

2022-07-08 07:48 UTC, merged